/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import main.login;

/**
 *
 * @author Administrator
 */
public class PayBill extends javax.swing.JFrame {

    /**
     * Creates new form PayBill
     */
    public PayBill() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        methodcombobox = new javax.swing.JComboBox<>();
        paybill = new javax.swing.JButton();
        enteramountfield = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        amountduefield = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        monthof1 = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        change = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();

        jLabel1.setBackground(new java.awt.Color(0, 204, 204));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 204, 204));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(0, 153, 153));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setBackground(new java.awt.Color(255, 255, 255));
        jLabel2.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("Pay Bill");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(61, 11, 367, 58));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 80));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel3.setText("Amount Due");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 120, 170, -1));

        methodcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        methodcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Payment Method", "Gcash", "Cash", "Bank" }));
        methodcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        methodcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                methodcomboboxActionPerformed(evt);
            }
        });
        jPanel1.add(methodcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 250, 170, 40));

        paybill.setBackground(new java.awt.Color(46, 134, 222));
        paybill.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paybill.setText("Pay");
        paybill.setBorder(null);
        paybill.setPreferredSize(new java.awt.Dimension(350, 40));
        paybill.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paybillActionPerformed(evt);
            }
        });
        jPanel1.add(paybill, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 410, 310, -1));

        enteramountfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        enteramountfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(enteramountfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 340, 170, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Account Number");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, 110, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel5.setText("Payment Method");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 220, 110, -1));

        amountduefield.setToolTipText("");
        amountduefield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        amountduefield.setEnabled(false);
        amountduefield.setName(""); // NOI18N
        amountduefield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(amountduefield, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 150, 170, -1));

        accountnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        accountnumber.setEnabled(false);
        accountnumber.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Enter Amount");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 110, -1));

        monthof1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        monthof1.setEnabled(false);
        monthof1.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(monthof1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel7.setText("Month");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        change.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        change.setEnabled(false);
        change.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel1.add(change, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 340, 170, -1));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel8.setText("Change");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(270, 310, 110, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 500));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void methodcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_methodcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_methodcomboboxActionPerformed

    private void paybillActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paybillActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paybillActionPerformed

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumber;
    private javax.swing.JTextField amountduefield;
    private javax.swing.JTextField change;
    private javax.swing.JTextField enteramountfield;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JComboBox<String> methodcombobox;
    private javax.swing.JTextField monthof1;
    private javax.swing.JButton paybill;
    // End of variables declaration//GEN-END:variables
}
