/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import static admin.ActionLogger.logAction;
import config.config;
import config.config.usersession;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.List;
import javax.swing.JOptionPane;
import main.login; 
import Bills.BillReceipt;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
/**
 *
 * @author Administrator
 */
public class user_dashboard extends javax.swing.JFrame {

   private Color defaultColor = new Color(44,62,80);
    private Color hoverColor = new Color(52,73,94);
    private config db = new config(); // Gi-fix gikan sa Object ngadto sa config
    public String name;
    private Connection con;
    

    // 2. CONSTRUCTOR (Diri ang tawag sa method)
    public user_dashboard(String loginName) {
        initComponents(); 
        this.name = loginName;
        welcometxt.setText("Welcome, " + loginName);
        
        loadUserBills(); // <--- GATAWAG SA METHOD
    }

    user_dashboard() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    // 3. METHOD DEFINITION (Ibutang ni sa ubos sa Constructor)
    private void loadUserBills() {
        DefaultTableModel model = (DefaultTableModel) mybillstable.getModel();
        model.setRowCount(0); // I-clear ang table sa dili pa sudlan

        try {
            // Koneksyon sa Database
            con = DriverManager.getConnection("jdbc:sqlite:ebs.db"); 
            String query = "SELECT * FROM bills WHERE username = ?";
            PreparedStatement pst = con.prepareStatement(query);
            pst.setString(1, this.name);
            
            ResultSet rs = pst.executeQuery();
            
            while(rs.next()) {
                // I-add ang data sa imong JTable
                String id = rs.getString("bill_id");
                String amount = rs.getString("amount");
                String status = rs.getString("status");
                model.addRow(new Object[]{id, amount, status});
            }
        } catch (Exception e) {
            System.out.println("Error: " + e.getMessage());
        }
    }

    // ... (Ang initComponents() ug uban pang generated code kasagaran naa sa ubos)

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        billsbtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        profilebtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        settingsbtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        firstName = new javax.swing.JLabel();
        welcometxt = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mybillstable = new javax.swing.JTable();
        viewreceipt = new javax.swing.JButton();
        viewstatementofaccount = new javax.swing.JButton();
        viewpendingbills = new javax.swing.JButton();
        viewpaidbills = new javax.swing.JButton();
        paymybills = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel3.setBackground(new java.awt.Color(0, 204, 204));
        jPanel3.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel3.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(0, 153, 153));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(0, 153, 153));
        logoutbtn.setForeground(new java.awt.Color(0, 153, 153));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 40));

        homebtn.setBackground(new java.awt.Color(0, 153, 153));
        homebtn.setForeground(new java.awt.Color(0, 153, 153));
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        homebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");
        homebtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        homebtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        billsbtn.setBackground(new java.awt.Color(0, 153, 153));
        billsbtn.setForeground(new java.awt.Color(0, 153, 153));
        billsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsbtnMouseExited(evt);
            }
        });
        billsbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bills");
        billsbtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        billsbtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(billsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        profilebtn.setBackground(new java.awt.Color(0, 153, 153));
        profilebtn.setForeground(new java.awt.Color(0, 153, 153));
        profilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilebtnMouseExited(evt);
            }
        });
        profilebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Profile");
        profilebtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        profilebtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        settingsbtn.setBackground(new java.awt.Color(0, 153, 153));
        settingsbtn.setForeground(new java.awt.Color(0, 153, 153));
        settingsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsbtnMouseExited(evt);
            }
        });
        settingsbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Settings");
        settingsbtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        settingsbtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(settingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PowerPay");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 220, -1));

        jPanel3.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 200, 600));

        firstName.setBackground(new java.awt.Color(0, 0, 0));
        firstName.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        firstName.setText("Name");
        jPanel3.add(firstName, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 40, 80, 30));

        welcometxt.setBackground(new java.awt.Color(0, 0, 0));
        welcometxt.setFont(new java.awt.Font("Lucida Calligraphy", 1, 18)); // NOI18N
        welcometxt.setText("Welcome,");
        jPanel3.add(welcometxt, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 40, 110, 30));

        mybillstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mybillstable);

        jPanel3.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 170, 450, 230));

        viewreceipt.setBackground(new java.awt.Color(255, 255, 255));
        viewreceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewreceipt.setText("Receipt");
        viewreceipt.setBorder(null);
        viewreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreceiptActionPerformed(evt);
            }
        });
        jPanel3.add(viewreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 130, 80, 30));

        viewstatementofaccount.setBackground(new java.awt.Color(255, 255, 255));
        viewstatementofaccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstatementofaccount.setText("Statement");
        viewstatementofaccount.setBorder(null);
        viewstatementofaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstatementofaccountActionPerformed(evt);
            }
        });
        jPanel3.add(viewstatementofaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(330, 130, 80, 30));

        viewpendingbills.setBackground(new java.awt.Color(255, 255, 255));
        viewpendingbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewpendingbills.setText("Pending Bills");
        viewpendingbills.setBorder(null);
        viewpendingbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpendingbillsActionPerformed(evt);
            }
        });
        jPanel3.add(viewpendingbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 130, 90, 30));

        viewpaidbills.setBackground(new java.awt.Color(255, 255, 255));
        viewpaidbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewpaidbills.setText("Paid Bills");
        viewpaidbills.setBorder(null);
        viewpaidbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpaidbillsActionPerformed(evt);
            }
        });
        jPanel3.add(viewpaidbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 130, 80, 30));

        paymybills.setBackground(new java.awt.Color(255, 255, 255));
        paymybills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymybills.setText("Pay Bill");
        paymybills.setBorder(null);
        paymybills.setPreferredSize(new java.awt.Dimension(350, 40));
        paymybills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymybillsActionPerformed(evt);
            }
        });
        jPanel3.add(paymybills, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 130, 80, 30));

        getContentPane().add(jPanel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 770, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseClicked
        new login().setVisible(true);
        logAction("User logged out");
        this.dispose();
    }//GEN-LAST:event_logoutbtnMouseClicked

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseEntered
        logoutbtn.setBackground(hoverColor);
    }//GEN-LAST:event_logoutbtnMouseEntered

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_logoutbtnMouseExited
        logoutbtn.setBackground(defaultColor);
    }//GEN-LAST:event_logoutbtnMouseExited

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_homebtnMouseClicked

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseEntered
        homebtn.setBackground(hoverColor);
    }//GEN-LAST:event_homebtnMouseEntered

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_homebtnMouseExited
        homebtn.setBackground(defaultColor);
    }//GEN-LAST:event_homebtnMouseExited

    private void billsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsbtnMouseClicked
        new UserBills().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_billsbtnMouseClicked

    private void billsbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsbtnMouseEntered
        billsbtn.setBackground(hoverColor);
    }//GEN-LAST:event_billsbtnMouseEntered

    private void billsbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_billsbtnMouseExited
        billsbtn.setBackground(defaultColor);
    }//GEN-LAST:event_billsbtnMouseExited

    private void profilebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMouseClicked
       new Profile(this.name).setVisible(true); 
    this.dispose();
    }//GEN-LAST:event_profilebtnMouseClicked

    private void profilebtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMouseEntered
        profilebtn.setBackground(hoverColor);
    }//GEN-LAST:event_profilebtnMouseEntered

    private void profilebtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_profilebtnMouseExited
        profilebtn.setBackground(defaultColor);
    }//GEN-LAST:event_profilebtnMouseExited

    private void settingsbtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsbtnMouseClicked
        new Settings().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_settingsbtnMouseClicked

    private void settingsbtnMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsbtnMouseEntered
        settingsbtn.setBackground(hoverColor);
    }//GEN-LAST:event_settingsbtnMouseEntered

    private void settingsbtnMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_settingsbtnMouseExited
        settingsbtn.setBackground(defaultColor);
    }//GEN-LAST:event_settingsbtnMouseExited

    private void viewreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewreceiptActionPerformed
    int row = mybillstable.getSelectedRow();
    
    if (row == -1) {
        JOptionPane.showMessageDialog(this, "Palihug pagpili og bill sa table una.");
    } else {
        // Kuhaa ang Bill ID gikan sa unang column (column 0)
        String billID = mybillstable.getValueAt(row, 0).toString();
        
        // I-pasa ang ID ngadto sa BillReceipt (kinahanglan nimo i-update ang constructor sa BillReceipt.java)
        BillReceipt receiptWindow = new BillReceipt(billID);
        receiptWindow.setVisible(true);
    }

    }//GEN-LAST:event_viewreceiptActionPerformed

    private void viewstatementofaccountActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewstatementofaccountActionPerformed
        int selectedRow = mybillstable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a bill to view statement.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String status = (String) mybillstable.getValueAt(selectedRow, 6);
        if (!"Pending".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "Statement of Account is only available for pending bills.", "Invalid Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int billId = (int) mybillstable.getValueAt(selectedRow, 0);

        // Open StatementOfAccount window and pass billId
        Bills.StatementOfAccount statementWindow = new Bills.StatementOfAccount();
        statementWindow.loadStatement(billId);
        statementWindow.setVisible(true);
    }//GEN-LAST:event_viewstatementofaccountActionPerformed

    private void viewpendingbillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpendingbillsActionPerformed
        loadUserBills();
    }//GEN-LAST:event_viewpendingbillsActionPerformed

    private void viewpaidbillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_viewpaidbillsActionPerformed
    usersession session = usersession.getInstance();
    int userId = session.getId();
    
    // Tawga ang imong load bills function gamit ang status nga 'Paid'
    loadBillsByStatus("Paid", userId);

    }//GEN-LAST:event_viewpaidbillsActionPerformed

    private void paymybillsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paymybillsActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_paymybillsActionPerformed

   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel billsbtn;
    private javax.swing.JLabel firstName;
    private javax.swing.JPanel homebtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JTable mybillstable;
    private javax.swing.JButton paymybills;
    private javax.swing.JPanel profilebtn;
    private javax.swing.JPanel settingsbtn;
    private javax.swing.JButton viewpaidbills;
    private javax.swing.JButton viewpendingbills;
    private javax.swing.JButton viewreceipt;
    private javax.swing.JButton viewstatementofaccount;
    public javax.swing.JLabel welcometxt;
    // End of variables declaration//GEN-END:variables


    private void logAction(String user_logged_out) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void setUserBillsTableModel(List<config.billsmodel> billsList) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadBillsByStatus(String paid, int userId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
