/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package user;

import config.billsmodel;
import java.awt.Color;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.List;
import javax.swing.JOptionPane;
import main.login;

/**
 *
 * @author Administrator
 */
public class UserBills extends javax.swing.JFrame {

    private Color hoverColor;
    private Color defaultColor;

    /**
     * Creates new form UserBills
     */
    public UserBills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">                          
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        mybillstable = new javax.swing.JTable();
        searchfield = new javax.swing.JTextField();
        searchbtn = new javax.swing.JButton();
        paymybills = new javax.swing.JButton();
        welcometxt2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        logoutbtn = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        homebtn = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        billsbtn = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        profilebtn = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        settingsbtn = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        viewpaidbills = new javax.swing.JButton();
        viewpendingbills = new javax.swing.JButton();
        viewstatementofaccount = new javax.swing.JButton();
        viewreceipt = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(244, 246, 249));
        jPanel5.setPreferredSize(new java.awt.Dimension(900, 600));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        mybillstable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        jScrollPane1.setViewportView(mybillstable);

        jPanel5.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, 640, 360));

        searchfield.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        searchfield.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(searchfield, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 100, 480, -1));

        searchbtn.setBackground(new java.awt.Color(44, 62, 80));
        searchbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        searchbtn.setText("Search");
        searchbtn.setBorder(null);
        searchbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        searchbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchbtnActionPerformed(evt);
            }
        });
        jPanel5.add(searchbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 100, 110, -1));

        paymybills.setBackground(new java.awt.Color(44, 62, 80));
        paymybills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        paymybills.setText("Pay Bill");
        paymybills.setBorder(null);
        paymybills.setPreferredSize(new java.awt.Dimension(350, 40));
        paymybills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paymybillsActionPerformed(evt);
            }
        });
        jPanel5.add(paymybills, new org.netbeans.lib.awtextra.AbsoluteConstraints(740, 50, 110, 40));

        welcometxt2.setBackground(new java.awt.Color(0, 0, 0));
        welcometxt2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        welcometxt2.setText("My Bills");
        jPanel5.add(welcometxt2, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 0, 150, 50));

        jPanel1.setBackground(new java.awt.Color(44, 62, 80));
        jPanel1.setPreferredSize(new java.awt.Dimension(200, 100));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutbtn.setBackground(new java.awt.Color(44, 62, 80));
        logoutbtn.setForeground(new java.awt.Color(44, 62, 80));
        logoutbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                logoutbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                logoutbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                logoutbtnMouseExited(evt);
            }
        });
        logoutbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel7.setBackground(new java.awt.Color(255, 255, 255));
        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Logout");
        logoutbtn.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        logoutbtn.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(logoutbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 350, 200, 40));

        homebtn.setBackground(new java.awt.Color(44, 62, 80));
        homebtn.setForeground(new java.awt.Color(44, 62, 80));
        homebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                homebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                homebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                homebtnMouseExited(evt);
            }
        });
        homebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setBackground(new java.awt.Color(255, 255, 255));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Home");
        homebtn.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        homebtn.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(homebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 150, 200, 40));

        billsbtn.setBackground(new java.awt.Color(44, 62, 80));
        billsbtn.setForeground(new java.awt.Color(44, 62, 80));
        billsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                billsbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                billsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                billsbtnMouseExited(evt);
            }
        });
        billsbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setBackground(new java.awt.Color(255, 255, 255));
        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Bills");
        billsbtn.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        billsbtn.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(billsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 200, 200, 40));

        profilebtn.setBackground(new java.awt.Color(44, 62, 80));
        profilebtn.setForeground(new java.awt.Color(44, 62, 80));
        profilebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                profilebtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                profilebtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                profilebtnMouseExited(evt);
            }
        });
        profilebtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Profile");
        profilebtn.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        profilebtn.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(profilebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 250, 200, 40));

        settingsbtn.setBackground(new java.awt.Color(44, 62, 80));
        settingsbtn.setForeground(new java.awt.Color(44, 62, 80));
        settingsbtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                settingsbtnMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                settingsbtnMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                settingsbtnMouseExited(evt);
            }
        });
        settingsbtn.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setBackground(new java.awt.Color(255, 255, 255));
        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Settings");
        settingsbtn.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 10, -1, -1));
        settingsbtn.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 10, -1, -1));

        jPanel1.add(settingsbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 300, 200, 40));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setText("PowerPay");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(-10, 30, 220, -1));

        jPanel5.add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, 600));

        viewpaidbills.setBackground(new java.awt.Color(44, 62, 80));
        viewpaidbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewpaidbills.setText("Paid Bills");
        viewpaidbills.setBorder(null);
        viewpaidbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpaidbillsActionPerformed(evt);
            }
        });
        jPanel5.add(viewpaidbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 50, 110, 40));

        viewpendingbills.setBackground(new java.awt.Color(44, 62, 80));
        viewpendingbills.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewpendingbills.setText("Pending Bills");
        viewpendingbills.setBorder(null);
        viewpendingbills.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewpendingbillsActionPerformed(evt);
            }
        });
        jPanel5.add(viewpendingbills, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 50, 110, 40));

        viewstatementofaccount.setBackground(new java.awt.Color(44, 62, 80));
        viewstatementofaccount.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewstatementofaccount.setText("Statement");
        viewstatementofaccount.setBorder(null);
        viewstatementofaccount.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewstatementofaccountActionPerformed(evt);
            }
        });
        jPanel5.add(viewstatementofaccount, new org.netbeans.lib.awtextra.AbsoluteConstraints(380, 50, 110, 40));

        viewreceipt.setBackground(new java.awt.Color(44, 62, 80));
        viewreceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        viewreceipt.setText("Receipt");
        viewreceipt.setBorder(null);
        viewreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                viewreceiptActionPerformed(evt);
            }
        });
        jPanel5.add(viewreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 50, 110, 40));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>                        

    private void searchbtnActionPerformed(java.awt.event.ActionEvent evt) throws SQLException {                                          
        // Search bills by keyword in all columns and display in billstable
        String searchText = searchfield.getText().trim();
        if (searchText.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter search text.");
            return;
        }
        String query = "SELECT b.b_id, u.account_number, b.bill_month, b.kwh_used, b.amount_due, b.due_date, b.status " +
                "FROM tbl_bill b " +
                "JOIN users u ON b.user_id = u.id " +
                "WHERE CAST(b.b_id AS CHAR) LIKE ? OR " +
                "u.account_number LIKE ? OR " +
                "b.bill_month LIKE ? OR " +
                "CAST(b.kwh_used AS CHAR) LIKE ? OR " +
                "CAST(b.amount_due AS CHAR) LIKE ? OR " +
                "CAST(b.due_date AS CHAR) LIKE ? OR " +
                "b.status LIKE ?";
        Connection con = db.getConnection();
        PreparedStatement pst = con.prepareStatement(query);
        String likeText = "%" + searchText + "%";
        for (int i = 1; i <= 7; i++) {
            pst.setString(i, likeText);
        }
        ResultSet rs = pst.executeQuery();
        // Convert ResultSet to List<billsmodel>
        java.util.List<config.billsmodel> billsList = new java.util.ArrayList<>();
        while (rs.next()) {
            config.billsmodel bill = new config.billsmodel(
                    rs.getInt("b_id"),
                    rs.getString("account_number"),
                    rs.getString("bill_month"),
                    rs.getInt("kwh_used"),
                    rs.getDouble("amount_due"),
                    rs.getDate("due_date"),
                    rs.getString("status")
            );
            billsList.add(bill);
        }
        rs.close();
        pst.close();
        con.close();
        // Set table model from billsList
        setUserBillsTableModel(billsList);
    }                                         

    private void paymybillsActionPerformed(java.awt.event.ActionEvent evt) {                                           
        // TODO add your handling code here:
    }                                          

    private void logoutbtnMouseClicked(java.awt.event.MouseEvent evt) {                                       
        new login().setVisible(true);
        logAction("User logged out");
        this.dispose();
    }                                      

    private void logoutbtnMouseEntered(java.awt.event.MouseEvent evt) {                                       
        logoutbtn.setBackground(hoverColor);
    }                                      

    private void logoutbtnMouseExited(java.awt.event.MouseEvent evt) {                                      
        logoutbtn.setBackground(defaultColor);
    }                                     

    private void homebtnMouseClicked(java.awt.event.MouseEvent evt) {                                     
        new user_dashboard().setVisible(true);
        this.dispose();
    }                                    

    private void homebtnMouseEntered(java.awt.event.MouseEvent evt) {                                     
        homebtn.setBackground(hoverColor);
    }                                    

    private void homebtnMouseExited(java.awt.event.MouseEvent evt) {                                    
        homebtn.setBackground(defaultColor);
    }                                   

    private void billsbtnMouseClicked(java.awt.event.MouseEvent evt) {                                      
        new UserBills().setVisible(true);
        this.dispose();
    }                                     

    private void billsbtnMouseEntered(java.awt.event.MouseEvent evt) {                                      
        billsbtn.setBackground(hoverColor);
    }                                     

    private void billsbtnMouseExited(java.awt.event.MouseEvent evt) {                                     
        billsbtn.setBackground(defaultColor);
    }                                    

    private void profilebtnMouseClicked(java.awt.event.MouseEvent evt) {                                        
        new Profile().setVisible(true);
        this.dispose();
    }                                       

    private void profilebtnMouseEntered(java.awt.event.MouseEvent evt) {                                        
        profilebtn.setBackground(hoverColor);
    }                                       

    private void profilebtnMouseExited(java.awt.event.MouseEvent evt) {                                       
        profilebtn.setBackground(defaultColor);
    }                                      

    private void settingsbtnMouseClicked(java.awt.event.MouseEvent evt) {                                         
        new Settings().setVisible(true);
        this.dispose();
    }                                        

    private void settingsbtnMouseEntered(java.awt.event.MouseEvent evt) {                                         
        settingsbtn.setBackground(hoverColor);
    }                                        

    private void settingsbtnMouseExited(java.awt.event.MouseEvent evt) {                                        
        settingsbtn.setBackground(defaultColor);
    }                                       

    private void viewpaidbillsActionPerformed(java.awt.event.ActionEvent evt) {                                              
        // TODO add your handling code here:
        usersession session = usersession.getInstance();
        int userId = session.getId();

        String query = "SELECT b.b_id, u.account_number, b.bill_month, b.kwh_used, b.amount_due, b.due_date, b.status " +
        "FROM tbl_bill b " +
        "JOIN users u ON b.user_id = u.id " +
        "WHERE b.user_id = ? AND b.status = 'Paid'";

        try (Connection con = db.getConnection();
            PreparedStatement pst = con.prepareStatement(query)) {

            pst.setInt(1, userId);
            ResultSet rs = pst.executeQuery();

            java.util.List<config.billsmodel> billsList = new java.util.ArrayList<>();
            while (rs.next()) {
                config.billsmodel bill = new config.billsmodel(
                    rs.getInt("b_id"),
                    rs.getString("account_number"),
                    rs.getString("bill_month"),
                    rs.getInt("kwh_used"),
                    rs.getDouble("amount_due"),
                    rs.getDate("due_date"),
                    rs.getString("status")
                );
                billsList.add(bill);
            }
            rs.close();

            setUserBillsTableModel(billsList);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error loading paid bills: " + e.getMessage());
        }
    }                                             

    private void viewpendingbillsActionPerformed(java.awt.event.ActionEvent evt) {                                                 
        loadUserBills();
    }                                                

    private void viewstatementofaccountActionPerformed(java.awt.event.ActionEvent evt) {                                                       
        int selectedRow = mybillstable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a bill to view statement.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String status = (String) mybillstable.getValueAt(selectedRow, 6);
        if (!"Pending".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "Statement of Account is only available for pending bills.", "Invalid Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int billId = (int) mybillstable.getValueAt(selectedRow, 0);

        // Open StatementOfAccount window and pass billId
        Bills.StatementOfAccount statementWindow = new Bills.StatementOfAccount();
        statementWindow.loadStatement(billId);
        statementWindow.setVisible(true);
    }                                                      

    private void viewreceiptActionPerformed(java.awt.event.ActionEvent evt) {                                            
        int selectedRow = mybillstable.getSelectedRow();
        if (selectedRow < 0) {
            JOptionPane.showMessageDialog(this, "Please select a bill to view receipt.", "No Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        String status = (String) mybillstable.getValueAt(selectedRow, 6);
        if (!"Paid".equalsIgnoreCase(status)) {
            JOptionPane.showMessageDialog(this, "Receipt is only available for paid bills.", "Invalid Selection", JOptionPane.WARNING_MESSAGE);
            return;
        }

        int billId = (int) mybillstable.getValueAt(selectedRow, 0);

        // Open BillsReceipt window and pass billId
        Bills.BillsReceipt receiptWindow = new Bills.BillsReceipt();
        receiptWindow.loadReceipt(billId);
        receiptWindow.setVisible(true);
    }                                           

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(UserBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new UserBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify                     
    private javax.swing.JPanel billsbtn;
    private javax.swing.JPanel homebtn;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JPanel logoutbtn;
    private javax.swing.JTable mybillstable;
    private javax.swing.JButton paymybills;
    private javax.swing.JPanel profilebtn;
    private javax.swing.JButton searchbtn;
    private javax.swing.JTextField searchfield;
    private javax.swing.JPanel settingsbtn;
    private javax.swing.JButton viewpaidbills;
    private javax.swing.JButton viewpendingbills;
    private javax.swing.JButton viewreceipt;
    private javax.swing.JButton viewstatementofaccount;
    private javax.swing.JLabel welcometxt2;
    // End of variables declaration                   

    private void setUserBillsTableModel(List<billsmodel> billsList) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void logAction(String user_logged_out) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private void loadUserBills() {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    private static class usersession {

        private static usersession getInstance() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }

        public usersession() {
        }

        private int getId() {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
