/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import config.config;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import admin.admin_dashboard;
import  user.user_dashboard;
/**
 *
 * @author Administrator
 */
public class login extends javax.swing.JFrame {

    private Object user;

    /**
     * Creates new form login
     */
    public login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        UserField = new javax.swing.JTextField();
        registerBtn = new javax.swing.JLabel();
        loginbtn = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        PasswordField = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        bg.setBackground(new java.awt.Color(244, 246, 249));
        bg.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setBackground(new java.awt.Color(0, 0, 0));
        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("  PowerPay");
        bg.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 10, 310, 70));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel2.setText("Username");
        bg.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, -1, -1));

        UserField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        UserField.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(UserField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 240, -1, -1));

        registerBtn.setBackground(new java.awt.Color(46, 134, 222));
        registerBtn.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        registerBtn.setForeground(new java.awt.Color(46, 134, 222));
        registerBtn.setText("Register");
        registerBtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                registerBtnMouseClicked(evt);
            }
        });
        bg.add(registerBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 470, -1, -1));

        loginbtn.setBackground(new java.awt.Color(46, 134, 222));
        loginbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        loginbtn.setText("Login");
        loginbtn.setBorder(null);
        loginbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        loginbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginbtnActionPerformed(evt);
            }
        });
        bg.add(loginbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 400, -1, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel4.setText("Password");
        bg.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 300, -1, -1));

        PasswordField.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        PasswordField.setPreferredSize(new java.awt.Dimension(350, 40));
        bg.add(PasswordField, new org.netbeans.lib.awtextra.AbsoluteConstraints(340, 330, -1, -1));

        jLabel3.setBackground(new java.awt.Color(0, 0, 0));
        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 20)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Login to Your Account");
        bg.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 130, 900, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 13)); // NOI18N
        jLabel6.setText("Don't have an account?");
        bg.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 470, -1, -1));

        getContentPane().add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-150, 0, 900, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void registerBtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_registerBtnMouseClicked
        register registerFrame = new register();
        registerFrame.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_registerBtnMouseClicked

    private void loginbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginbtnActionPerformed
                                            
    String user = UserField.getText().trim();
    String pass = new String(PasswordField.getPassword()).trim();

    // 1. Check kung empty ba ang fields
    if (user.isEmpty() || pass.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Palihog puy-i ang tanan!", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    config db = new config();

    try {
        // 2. Query para i-check ang credentials
        String query = "SELECT * FROM users WHERE u_username = '" + user + "' AND u_password = '" + pass + "'";
        java.sql.ResultSet rs = db.getData(query);

        if (rs.next()) {
            // Kuhaon ang data gikan sa database columns
            String status = rs.getString("u_status");
            String role = rs.getString("u_role");
            String fNameFromDB = rs.getString("u_firstname"); // Mao ni ang tinuod nga ngalan

            // 3. Check kung Active ba ang account
            if (status.equalsIgnoreCase("Active")) {
                
                if (role.equalsIgnoreCase("Admin")) {
                    JOptionPane.showMessageDialog(this, "Login Successful! Welcome Admin " + fNameFromDB);
                    
                    // I-pasa ang fNameFromDB ngadto sa admin_dashboard constructor
                    admin.admin_dashboard ads = new admin.admin_dashboard(fNameFromDB);
                    ads.setVisible(true);
                    this.dispose(); 
                } 
                else if (role.equalsIgnoreCase("User")) {
                    JOptionPane.showMessageDialog(this, "Login Successful! Welcome " + fNameFromDB);
                    
                    // I-pasa ang fNameFromDB ngadto sa user_dashboard constructor
                    user.user_dashboard usd = new user.user_dashboard(fNameFromDB);
                    usd.setVisible(true);
                    this.dispose(); 
                }
            } 
            else {
                // Kung 'Pending' o 'Inactive' ang status
                JOptionPane.showMessageDialog(this, "Ang imong account kay " + status + ". Kontaka ang Admin.", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } else {
            // Kung mali ang username o password
            JOptionPane.showMessageDialog(this, "Sayop ang Username o Password!", "Login Failed", JOptionPane.ERROR_MESSAGE);
        }
        rs.close(); 
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Database Error: " + e.getMessage());
    }


         
  
        
    }//GEN-LAST:event_loginbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPasswordField PasswordField;
    private javax.swing.JTextField UserField;
    private javax.swing.JPanel bg;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JButton loginbtn;
    private javax.swing.JLabel registerBtn;
    // End of variables declaration//GEN-END:variables
}
