/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills;

import config.config;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;

/**
 *
 * @author Administrator
 */
public class AddBills extends javax.swing.JFrame {

    /**
     * Creates new form AddBills
     */
    public AddBills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        monthcombobox = new javax.swing.JComboBox<>();
        addbillbtn = new javax.swing.JButton();
        kWh = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Bill");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Due Date (MM/DD/YYYY)");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("kWh");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        monthcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "December" }));
        monthcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        monthcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcomboboxActionPerformed(evt);
            }
        });
        jPanel5.add(monthcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 40));

        addbillbtn.setBackground(new java.awt.Color(46, 134, 222));
        addbillbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbillbtn.setText("Add");
        addbillbtn.setBorder(null);
        addbillbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        addbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillbtnActionPerformed(evt);
            }
        });
        jPanel5.add(addbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, -1));

        kWh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        kWh.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(kWh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, -1));

        accountnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        accountnumber.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Account Number");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Month");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        duedate.setToolTipText("");
        duedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        duedate.setName(""); // NOI18N
        duedate.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthcomboboxActionPerformed

    private void addbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillbtnActionPerformed
        // Get input values
        String accountNum = accountnumber.getText().trim();
        String kWhText = kWh.getText().trim();
        String billMonth = (String) monthcombobox.getSelectedItem();
        String dueDateText = duedate.getText().trim();

        // Validate account number
        if (accountNum.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Please enter an account number.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate kWh used
        double kWhUsed;
        try {
            kWhUsed = Double.parseDouble(kWhText);
            if (kWhUsed < 0) {
                JOptionPane.showMessageDialog(this, "kWh used must be a positive number.", "Input Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Please enter a valid number for kWh used.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate bill month
        if (billMonth == null || billMonth.equals("Select Month")) {
            JOptionPane.showMessageDialog(this, "Please select a bill month.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Validate due date format MM/DD/YYYY
        if (!dueDateText.matches("^\\d{2}/\\d{2}/\\d{4}$")) {
            JOptionPane.showMessageDialog(this, "Please enter due date in MM/DD/YYYY format.", "Input Error", JOptionPane.ERROR_MESSAGE);
            return;
        }

        // Calculate amount due
        double amountDue = 0.0;

        // Set default status
        String status = "Pending";

        // Database operations
        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rs = null;

        try {
            conn = config.getConnection();

            // Query to get user_id from account_number
            String getUserIdQuery = "SELECT id FROM users WHERE account_number = ?";
            pst = conn.prepareStatement(getUserIdQuery);
            pst.setString(1, accountNum);
            rs = pst.executeQuery();

            int userId = -1;
            if (rs.next()) {
                userId = rs.getInt("id");
            } else {
                JOptionPane.showMessageDialog(this, "Account number not found.", "Error", JOptionPane.ERROR_MESSAGE);
                return;
            }
            rs.close();
            pst.close();

            // Query to get current rate_perkWh
            String getRateQuery = "SELECT rate_perkWh FROM tbl_bill LIMIT 1";
            pst = conn.prepareStatement(getRateQuery);
            rs = pst.executeQuery();
            double ratePerkWh = 0.0;
            if (rs.next()) {
                ratePerkWh = rs.getDouble("rate_perkWh");
            }
            rs.close();
            pst.close();

            // Calculate amount due using rate_perkWh
            amountDue = kWhUsed * ratePerkWh;

            // Convert dueDateText to java.sql.Date
            SimpleDateFormat sdf = new SimpleDateFormat("MM/dd/yyyy");
            java.util.Date parsedDate = sdf.parse(dueDateText);
            java.sql.Date dueDate = new java.sql.Date(parsedDate.getTime());

            // Insert bill query
            String insertQuery = "INSERT INTO tbl_bill (user_id, bill_month, kwh_used, amount_due, due_date, status, rate_perkWh) VALUES (?, ?, ?, ?, ?, ?, ?)";
            pst = conn.prepareStatement(insertQuery);
            pst.setInt(1, userId);
            pst.setString(2, billMonth);
            pst.setDouble(3, kWhUsed);
            pst.setDouble(4, amountDue);
            pst.setDate(5, dueDate);
            pst.setString(6, status);
            pst.setDouble(7, ratePerkWh);

            int rowsInserted = pst.executeUpdate();
            if (rowsInserted > 0) {
                String message = String.format("Bill added successfully!\nAccount Number: %s\nkWh Used: %.2f\nAmount Due: %.2f\nMonth: %s\nDue Date: %s\nStatus: %s\nRate per kWh: %.2f",
                    accountNum, kWhUsed, amountDue, billMonth, dueDateText, status, ratePerkWh);
                JOptionPane.showMessageDialog(this, message, "Success", JOptionPane.INFORMATION_MESSAGE);

                // Clear fields after adding
                accountnumber.setText("");
                kWh.setText("");
                monthcombobox.setSelectedIndex(0);
                duedate.setText("");
                this.dispose();
            } else {
                JOptionPane.showMessageDialog(this, "Failed to add bill.", "Error", JOptionPane.ERROR_MESSAGE);
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Database error: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
        } catch (ParseException e) {
            JOptionPane.showMessageDialog(this, "Invalid date format.", "Error", JOptionPane.ERROR_MESSAGE);
        } finally {
            try {
                if (rs != null) rs.close();
                if (pst != null) pst.close();
                if (conn != null) conn.close();
            } catch (SQLException e) {
                // Ignore close errors
            }
        }
    }//GEN-LAST:event_addbillbtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AddBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AddBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AddBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AddBills.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AddBills().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumber;
    private javax.swing.JButton addbillbtn;
    private javax.swing.JTextField duedate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField kWh;
    private javax.swing.JComboBox<String> monthcombobox;
    // End of variables declaration//GEN-END:variables

    private static class Connection {

        public Connection() {
        }

        private PreparedStatement prepareStatement(String userIdQuery) {
            throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
        }
    }
}
