/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills;

import config.config; // Para sa imong database connection
import java.sql.Connection; // Tinuod nga SQL Connection
import java.sql.PreparedStatement; // Tinuod nga SQL PreparedStatement
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;
import java.text.ParseException;
import java.text.SimpleDateFormat;
import main.login;

/**
 *
 * @author Administrator
 */
public class AddBills extends javax.swing.JFrame {

    /**
     * Creates new form AddBills
     */
    public AddBills() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        monthcombobox = new javax.swing.JComboBox<>();
        addbillbtn = new javax.swing.JButton();
        kWh = new javax.swing.JTextField();
        accountnumber = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        duedate = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel5.setBackground(new java.awt.Color(255, 255, 255));
        jPanel5.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel6.setBackground(new java.awt.Color(44, 62, 80));

        jLabel5.setBackground(new java.awt.Color(255, 255, 255));
        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Add Bill");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 500, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, 60, Short.MAX_VALUE)
        );

        jPanel5.add(jPanel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 60));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel6.setText("Due Date (MM/DD/YYYY)");
        jPanel5.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 220, 170, -1));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel9.setText("kWh");
        jPanel5.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 110, -1, -1));

        monthcombobox.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        monthcombobox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Month", "January", "February", "March", "April", "May", "June", "July", "August", "September", "October", "December" }));
        monthcombobox.setPreferredSize(new java.awt.Dimension(350, 40));
        monthcombobox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                monthcomboboxActionPerformed(evt);
            }
        });
        jPanel5.add(monthcombobox, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 250, 170, 40));

        addbillbtn.setBackground(new java.awt.Color(46, 134, 222));
        addbillbtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        addbillbtn.setText("Add");
        addbillbtn.setBorder(null);
        addbillbtn.setPreferredSize(new java.awt.Dimension(350, 40));
        addbillbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addbillbtnActionPerformed(evt);
            }
        });
        jPanel5.add(addbillbtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 350, 310, -1));

        kWh.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        kWh.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(kWh, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 150, 170, -1));

        accountnumber.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        accountnumber.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(accountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 150, 170, -1));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel10.setText("Account Number");
        jPanel5.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 110, 110, -1));

        jLabel11.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel11.setText("Month");
        jPanel5.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, 110, -1));

        duedate.setToolTipText("");
        duedate.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(200, 200, 200)));
        duedate.setName(""); // NOI18N
        duedate.setPreferredSize(new java.awt.Dimension(350, 40));
        jPanel5.add(duedate, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 250, 170, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel5, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void monthcomboboxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_monthcomboboxActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_monthcomboboxActionPerformed

    private void addbillbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addbillbtnActionPerformed
     try {
    // Kinahanglan 'config.connectDB()' ra kay static man ang method sa imong config.java
    Connection conn = config.connectDB(); 
    
    if (conn != null) {
        String userIdQuery = "SELECT u_id FROM users WHERE u_account_number = ?";
        PreparedStatement pst = conn.prepareStatement(userIdQuery);
        
        pst.setString(1, accountnumber.getText());
        ResultSet rs = pst.executeQuery();
        
        if (rs.next()) {
            int u_id = rs.getInt("u_id");
            // Ipadayon imong logic diri...
        }
        
        rs.close();
        pst.close();
        conn.close();
    }
} catch (SQLException ex) {
    JOptionPane.showMessageDialog(this, "Database Error: " + ex.getMessage());
}
       
    }//GEN-LAST:event_addbillbtnActionPerformed

    public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField accountnumber;
    private javax.swing.JButton addbillbtn;
    private javax.swing.JTextField duedate;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JTextField kWh;
    private javax.swing.JComboBox<String> monthcombobox;
    // End of variables declaration//GEN-END:variables

}
