/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Bills;

import main.login;

/**
 *
 * @author Administrator
 */
public class BillReceipt extends javax.swing.JFrame {

    /**
     * Creates new form BillReciept
     */
    public BillReceipt() {
        initComponents();
    }

    public BillReceipt(String billID) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        customername = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        customeraccountnumber = new javax.swing.JLabel();
        billid = new javax.swing.JLabel();
        paymentid = new javax.swing.JLabel();
        paymentdate = new javax.swing.JLabel();
        paymentmethod = new javax.swing.JLabel();
        amtpaid = new javax.swing.JLabel();
        printreceipt = new javax.swing.JButton();
        closebtn = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(46, 134, 222));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("SansSerif", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Payment Receipt");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-7, -5, 610, 70));

        jPanel1.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 60));

        jLabel2.setBackground(new java.awt.Color(46, 134, 222));
        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(46, 134, 222));
        jLabel2.setText("Amount Paid:");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 420, 150, 30));

        jLabel3.setText("                _________________________________________________________________________________");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 110, 680, -1));

        jLabel4.setText("                _________________________________________________________________________________");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(-30, 240, 680, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(51, 51, 51));
        jLabel5.setText("Payment Details");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 220, 160, 30));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(51, 51, 51));
        jLabel6.setText("Customer Info");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 90, 110, 30));

        customername.setBackground(new java.awt.Color(46, 134, 222));
        customername.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customername.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customername.setText("Name:");
        jPanel1.add(customername, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 130, 110, 30));

        jLabel8.setBackground(new java.awt.Color(46, 134, 222));
        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(46, 134, 222));
        jLabel8.setText("Account Number:");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 170, 150, 30));

        jLabel9.setBackground(new java.awt.Color(46, 134, 222));
        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(46, 134, 222));
        jLabel9.setText("Bill ID:");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 260, 150, 30));

        jLabel10.setBackground(new java.awt.Color(46, 134, 222));
        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(46, 134, 222));
        jLabel10.setText("Payment ID:");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, 150, 30));

        jLabel11.setBackground(new java.awt.Color(46, 134, 222));
        jLabel11.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(46, 134, 222));
        jLabel11.setText("Payment Date:");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 340, 150, 30));

        jLabel12.setBackground(new java.awt.Color(46, 134, 222));
        jLabel12.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(46, 134, 222));
        jLabel12.setText("Payment Method");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 380, 150, 30));

        jLabel13.setBackground(new java.awt.Color(46, 134, 222));
        jLabel13.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(46, 134, 222));
        jLabel13.setText("Name:");
        jPanel1.add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 130, 110, 30));

        customeraccountnumber.setBackground(new java.awt.Color(46, 134, 222));
        customeraccountnumber.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        customeraccountnumber.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        customeraccountnumber.setText("AccNumber");
        jPanel1.add(customeraccountnumber, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 170, 110, 30));

        billid.setBackground(new java.awt.Color(46, 134, 222));
        billid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        billid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        billid.setText("BillID");
        jPanel1.add(billid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 260, 160, 30));

        paymentid.setBackground(new java.awt.Color(46, 134, 222));
        paymentid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentid.setText("PaymentID");
        jPanel1.add(paymentid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 300, 160, 30));

        paymentdate.setBackground(new java.awt.Color(46, 134, 222));
        paymentdate.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentdate.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentdate.setText("PaymentDate");
        jPanel1.add(paymentdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 340, 160, 30));

        paymentmethod.setBackground(new java.awt.Color(46, 134, 222));
        paymentmethod.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        paymentmethod.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        paymentmethod.setText("PaymentMethod");
        jPanel1.add(paymentmethod, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 380, 160, 30));

        amtpaid.setBackground(new java.awt.Color(46, 134, 222));
        amtpaid.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        amtpaid.setHorizontalAlignment(javax.swing.SwingConstants.RIGHT);
        amtpaid.setText("AmountPaid");
        jPanel1.add(amtpaid, new org.netbeans.lib.awtextra.AbsoluteConstraints(420, 420, 160, 30));

        printreceipt.setBackground(new java.awt.Color(46, 134, 222));
        printreceipt.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        printreceipt.setText("Print");
        printreceipt.setBorder(null);
        printreceipt.setPreferredSize(new java.awt.Dimension(350, 40));
        printreceipt.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                printreceiptMouseClicked(evt);
            }
        });
        printreceipt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                printreceiptActionPerformed(evt);
            }
        });
        jPanel1.add(printreceipt, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 470, 140, 20));

        closebtn.setBackground(new java.awt.Color(46, 134, 222));
        closebtn.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        closebtn.setText("Close");
        closebtn.setBorder(null);
        closebtn.setPreferredSize(new java.awt.Dimension(350, 40));
        closebtn.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                closebtnMouseClicked(evt);
            }
        });
        closebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                closebtnActionPerformed(evt);
            }
        });
        jPanel1.add(closebtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 470, 140, 20));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 600, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 600, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 500, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 500, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void printreceiptMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_printreceiptMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_printreceiptMouseClicked

    private void printreceiptActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_printreceiptActionPerformed
        // Use PanelPrinter to print the jPanel1
        config.Print printer = new config.Print(jPanel1);
        printer.printPanel();
    }//GEN-LAST:event_printreceiptActionPerformed

    private void closebtnMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_closebtnMouseClicked
        this.dispose();
    }//GEN-LAST:event_closebtnMouseClicked

    private void closebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_closebtnActionPerformed
        this.dispose();
    }//GEN-LAST:event_closebtnActionPerformed

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
    java.awt.EventQueue.invokeLater(new Runnable() {
        public void run() {
           
            javax.swing.JOptionPane.showMessageDialog(null, "Direct access is forbidden! Please login first.");
            new login().setVisible(true);
        }
    });

    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel amtpaid;
    private javax.swing.JLabel billid;
    private javax.swing.JButton closebtn;
    private javax.swing.JLabel customeraccountnumber;
    private javax.swing.JLabel customername;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel paymentdate;
    private javax.swing.JLabel paymentid;
    private javax.swing.JLabel paymentmethod;
    private javax.swing.JButton printreceipt;
    // End of variables declaration//GEN-END:variables

    public void loadReceipt(int billId) {
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }
}
